#微服务注册到eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    perferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
server:
  port: 9004
spring:
  application:
    name: ihrm-social-securitys #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8
    username: root
    password: 111111
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
ai_appId: 18533226
ai_apiKey: fNPCkRCr9jQSYuWF3P53WdDs
ai_secretKey: NSXFLWyzTBhLF0E8X7c8h4UvUzsZSAq7
ai_imageType: BASE64
ai_groupId: ArvinYL
qr_url: https://localhost:8080/#/facelogin

